package(default_visibility = ["//visibility:public"])

cc_library(
    name = "rtt",
    srcs = [
        "src/SEGGER_RTT.c",
        "src/SEGGER_RTT_printf.c",
    ],
    includes = ["include"],
    hdrs = [
        "include/SEGGER_RTT.h",
        "include/SEGGER_RTT_Conf.h",
    ],
)
